version: '3.9'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    command: >
      postgres -c listen_addresses='*'

  server:
    build: ./server
    ports:
      - 5050:5050

    volumes:
      - .:/usr/src/app
    environment:
      POSTGRES_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SALT_ROUNDS: ${SALT_ROUNDS}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      PORT: 5050

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://${IP_ADDRESS}:5050
      VITE_PROVINCE_URL: ${PROVINCE_URL}
      VITE_MAILER_URL: ${MAILER_URL}
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  pgdata:
